version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=http://brendonirma-in-answer-genius-9f96.twc1.net
    restart: unless-stopped